// 中文默认
const locale = {
    nick: '昵称',
    nickError: '昵称不能少于3个字符',
    mail: '邮箱',
    mailError: '请填写正确的邮件地址',
    link: '网址',
    optional: '可选',
    placeholder: '留言讓大家知道你來了！',
    sofa: '来发评论吧~',
    submit: '提交',
    like: '喜欢',
    cancelLike: '取消喜欢',
    reply: '回复',
    cancelReply: '取消回复',
    comment: '评论',
    refresh: '刷新',
    more: '加载更多...',
    preview: '预览',
    emoji: '表情',
    uploadImage: '上传图片',
    seconds: '秒前',
    minutes: '分钟前',
    hours: '小时前',
    days: '天前',
    now: '刚刚',
    uploading: '正在上传',
    login: '登录',
    logout: '退出',
    admin: '博主',
    sticky: '置顶',
    word: '字',
    wordHint: '评论字数应在 $0 到 $1 字之间！\n当前字数：$2',
    anonymous: '匿名',
    level0: '潜水',
    level1: '冒泡',
    level2: '吐槽',
    level3: '活跃',
    level4: '话痨',
    level5: '传说',
    gif: '表情包',
    gifSearchPlaceholder: '搜索表情包',
    profile: '个人资料',
    approved: '通过',
    waiting: '待审核',
    spam: '垃圾',
    unsticky: '取消置顶',
    oldest: '按倒序',
    latest: '按正序',
    hottest: '按热度',
    reactionTitle: '你认为这篇文章怎么样？',
  };
  
  Waline.init({
    el: '#waline',
    serverURL: 'https://waline-l2lpo3cvv-wmeffect.vercel.app/',
    path: window.location.pathname,
    meta: ['nick', 'mail', 'link'],
    requiredMeta: [],
    lang: 'zh-CN',
    emoji: [
      'https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo',
      'https://unpkg.com/@waline/emojis@1.1.0/bilibili',
      'https://unpkg.com/@waline/emojis@1.1.0/alus',
      'https://unpkg.com/@waline/emojis@1.1.0/bmoji',
      'https://unpkg.com/@waline/emojis@1.1.0/qq',
      'https://unpkg.com/@waline/emojis@1.1.0/tieba'
      ],
    dark: 'html[data-user-color-scheme="dark"]',
    wordLimit: 0,
    pageSize: 10,
    reaction: [
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_thumbsup.png',
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_helpless.png',
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_wise.png',
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_pick_nose.png',
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_expressionless.png',
        'https://unpkg.com/@waline/emojis@1.1.0/alus/alus_sob.png',
    ],
    locale,
  });
  